#! /bin/bash
#
#$Author: ee364a09 $
#$Date: 2016-01-12 14:29:53 -0500 (Tue, 12 Jan 2016) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364a09/Lab00/Script1 $
#$Revision: 83925 $

Num_Of_PAram=$#
Param_Values=$@
echo "The program received $Num_Of_Param parameters"
echo "The parameters are :"
echo "$Param_Values"
echo "The 2nd parameter is \"$2"\"
echo "The 4th parameter is \"$4"\"
exit 0
