#! /bin/bash
#
#$Author: ee364a09 $
#$Date: 2016-01-12 14:54:12 -0500 (Tue, 12 Jan 2016) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364a09/Lab00/Script3 $
#$Revision: 83976 $

Parameter_value=$@
loop_counter=$Parameter_value

while (($loop_counter>=0))
do
if (($loop_counter%3==0))
then
echo "$loop_counter"
fi
let loop_counter=$loop_counter-1
done

exit 0

